# Generated by Django 3.1 on 2020-08-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_fee', models.FloatField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubletGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sublet_gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubletOwnerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sublet_owner_name', models.CharField(max_length=200)),
                ('sublet_owner_email', models.CharField(max_length=200)),
                ('sublet_owner_phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubletPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sublet_company', models.CharField(max_length=100)),
                ('sublet_address', models.CharField(max_length=800)),
                ('website', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Subtenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=800)),
                ('photo_id', models.ImageField(upload_to='img')),
                ('date', models.DateTimeField(auto_now=True)),
                ('signature', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubletListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sublist_price', models.FloatField(default=0)),
                ('sublet_start_date', models.DateTimeField()),
                ('sublet_end_date', models.DateTimeField()),
                ('sublet_status', models.IntegerField(default=1)),
                ('parking_cost', models.FloatField(default=0)),
                ('total_room', models.IntegerField(default=1)),
                ('room_number', models.CharField(max_length=100)),
                ('utilities', models.CharField(max_length=5000)),
                ('sublet_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sublets.subletgender')),
                ('sublet_legal_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sublets.legalfee')),
                ('sublet_owner_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sublets.subletownerinfo')),
                ('sublet_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sublets.subletplace')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(null=True, upload_to='img')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sublets.subletlisting')),
            ],
        ),
    ]
