# Generated by Django 3.1 on 2020-08-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublets', '0003_auto_20200821_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtenant',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
