# Generated by Django 3.1 on 2020-08-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublets', '0004_auto_20200823_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtenant',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
