# Generated by Django 3.1 on 2020-08-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sublets', '0005_subtenant_payment_status'),
        ('sublets', '0003_auto_20200821_2030'),
    ]

    operations = [
    ]
