# Generated by Django 3.1 on 2020-08-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublets', '0007_subtenant_gr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subletplace',
            name='landlord',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
