# Generated by Django 3.1 on 2020-08-28 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublets', '0011_auto_20200828_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='subletlisting',
            name='sublet_description',
            field=models.TextField(default='No description.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='subletlisting',
            name='end_date_search',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 13, 30, 25, 220229)),
        ),
        migrations.AlterField(
            model_name='subletlisting',
            name='start_date_search',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 13, 30, 25, 220229)),
        ),
    ]
