# Generated by Django 3.1 on 2020-08-30 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublets', '0015_auto_20200829_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subletlisting',
            name='end_date_search',
            field=models.DateField(default=datetime.datetime(2020, 8, 30, 12, 7, 5, 651846)),
        ),
        migrations.AlterField(
            model_name='subletlisting',
            name='start_date_search',
            field=models.DateField(default=datetime.datetime(2020, 8, 30, 12, 7, 5, 651846)),
        ),
    ]
