# Generated by Django 3.1 on 2020-08-30 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sublets', '0018_auto_20200830_1816'),
        ('sublets', '0019_auto_20200830_1858'),
    ]

    operations = [
    ]
