# Generated by Django 3.1 on 2020-08-30 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublets', '0022_auto_20200830_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subletlisting',
            name='end_date_search',
            field=models.DateField(default=datetime.datetime(2020, 8, 30, 19, 41, 1, 910520)),
        ),
        migrations.AlterField(
            model_name='subletlisting',
            name='start_date_search',
            field=models.DateField(default=datetime.datetime(2020, 8, 30, 19, 41, 1, 910520)),
        ),
        migrations.AlterField(
            model_name='subtenant',
            name='photo_id',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
