# Generated by Django 3.1 on 2020-08-31 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublets', '0023_auto_20200830_1941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubletPlace',
            new_name='SubletBuilding',
        ),
        migrations.AlterField(
            model_name='subletlisting',
            name='end_date_search',
            field=models.DateField(default=datetime.datetime(2020, 8, 31, 12, 38, 28, 181653)),
        ),
        migrations.AlterField(
            model_name='subletlisting',
            name='start_date_search',
            field=models.DateField(default=datetime.datetime(2020, 8, 31, 12, 38, 28, 181653)),
        ),
    ]
