# Generated by Django 3.1 on 2020-08-31 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublets', '0024_auto_20200831_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subletlisting',
            old_name='sublet_place',
            new_name='sublet_building',
        ),
        migrations.AlterField(
            model_name='subletlisting',
            name='end_date_search',
            field=models.DateField(default=datetime.datetime(2020, 8, 31, 12, 43, 12, 112664)),
        ),
        migrations.AlterField(
            model_name='subletlisting',
            name='start_date_search',
            field=models.DateField(default=datetime.datetime(2020, 8, 31, 12, 43, 12, 112664)),
        ),
    ]
